packages:
  - packages/*
  - crates/wasm/
verifyDepsBeforeRun: false
allowBuilds:
  esbuild: false
  protobufjs: false
  sharp: false
  wasm-pack: true
  workerd: false
minimumReleaseAgeExclude:
  - pkg-pr-new@0.0.78
