#!/usr/bin/env python
"""Strip the deterministic DFT kernel tensors out of baked htdemucs ONNX exports.

Each baked export carries ~136 MB of Constant tensors (STFT cos/sin conv kernels, iSTFT
inverse basis, window-sum envelope) that are byte-identical across every model — deterministic
data generated by demucs/stft.py + istft.py at module init (the iSTFT basis via
torch.linalg.pinv, which is why we treat the baked bytes as authoritative rather than
re-synthesizing).

This rewrites each model: large Constant nodes become initializers whose data lives in ONE
shared external file (dft.bin) next to the models. ONNX Runtime resolves external data
natively at session load — consumers (Python ORT, Rust ort crate) need no changes.

5 x 304 MB -> 5 x ~168 MB + one 136 MB dft.bin.

Usage:
    uv run python tools/model-export/strip_dft.py \
        --models htdemucs htdemucs_ft_drums htdemucs_ft_bass \
        htdemucs_ft_other htdemucs_ft_vocals --src data/onnx --out data/onnx-lean
"""

import argparse
import hashlib
from pathlib import Path

import onnx
from onnx import TensorProto

THRESHOLD = 1 << 20  # tensors >= 1 MB are considered kernel data
DFT_FILE = "dft.bin"
ALIGN = 64


def strip_models(models: list[str], src: Path, out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    # name -> (offset, length, sha256) in dft.bin; filled by the first model,
    # verified identical by every subsequent one
    layout: dict[str, tuple[int, int, str]] = {}
    blob = bytearray()

    for name in models:
        model = onnx.load(str(src / f"{name}.onnx"))
        graph = model.graph
        stripped = []
        keep_nodes = []
        for node in graph.node:
            tensor = None
            if node.op_type == "Constant":
                for attr in node.attribute:
                    if attr.t.raw_data and len(attr.t.raw_data) >= THRESHOLD:
                        tensor = attr.t
            if tensor is None:
                keep_nodes.append(node)
                continue

            out_name = node.output[0]
            data = tensor.raw_data
            digest = hashlib.sha256(data).hexdigest()
            if out_name in layout:
                off, length, known = layout[out_name]
                if (len(data), digest) != (length, known):
                    raise SystemExit(
                        f"{name}: tensor {out_name} differs from previously recorded content — "
                        f"the shared-kernel assumption is broken, aborting"
                    )
            else:
                if len(blob) % ALIGN:
                    blob.extend(b"\0" * (ALIGN - len(blob) % ALIGN))
                layout[out_name] = (len(blob), len(data), digest)
                blob.extend(data)
            off, length, _ = layout[out_name]

            init = TensorProto()
            init.name = out_name
            init.data_type = tensor.data_type
            init.dims.extend(tensor.dims)
            init.data_location = TensorProto.EXTERNAL
            for k, v in (("location", DFT_FILE), ("offset", str(off)), ("length", str(length))):
                entry = init.external_data.add()
                entry.key = k
                entry.value = v
            graph.initializer.append(init)
            stripped.append((out_name, length))

        del graph.node[:]
        graph.node.extend(keep_nodes)
        out_path = out / f"{name}.onnx"
        onnx.save(model, str(out_path))
        total = sum(l for _, l in stripped)
        print(f"{name}: stripped {len(stripped)} tensors ({total/1e6:.1f} MB) -> "
              f"{out_path.stat().st_size/1e6:.1f} MB")

    dft_path = out / DFT_FILE
    dft_path.write_bytes(bytes(blob))
    print(f"{DFT_FILE}: {len(blob)/1e6:.1f} MB, sha256 {hashlib.sha256(bytes(blob)).hexdigest()}")
    for tname, (off, length, digest) in layout.items():
        print(f"  {tname}  offset={off} length={length} sha256={digest[:16]}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--models", nargs="+", required=True)
    parser.add_argument("--src", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    strip_models(args.models, args.src, args.out)


if __name__ == "__main__":
    main()
